import {StyleSheet} from 'react-native';
import {perfectSize, colors, fonts} from '../../theme';
export default styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: perfectSize(56),
    padding: perfectSize(23),
    backgroundColor: colors.primaryBackgroundColor,
  },
  backArrowContainer: {
    height: perfectSize(30),
    width: perfectSize(30),
  },
  backArrow: {
    height: '100%',
    width: '100%',
    resizeMode: 'contain',
    tintColor: colors.primaryLightColor,
    opacity: 0.5,
  },
  title: {
    textAlign: 'center',
    fontFamily: fonts.quicksandBold,
    fontSize: perfectSize(55),
    color: colors.primaryLightColor,
    opacity: 0.5,
  },
  textInput: {
    padding: perfectSize(20),
    height: perfectSize(70),
    width: '100%',
    backgroundColor: 'rgba(0,0,0,0.1)',
    borderRadius: perfectSize(12),
    fontSize: perfectSize(23),
    fontFamily: fonts.quicksandBold,
    color: colors.primaryLightColor,
    marginTop: '40%',
  },
  forgotPassword: {
    textAlign: 'right',
    fontFamily: fonts.avenirHeavy,
    fontSize: perfectSize(15),
    color: colors.primaryLightColor,
    top: perfectSize(20),
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  bottomView: {
    width: '100%',
    alignSelf: 'center',
    paddingBottom: '10%',
    backgroundColor: colors.primaryBackgroundColor,
  },
  buttonContainer: {
    height: perfectSize(60),
    width: perfectSize(300),
    borderRadius: perfectSize(30),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryLightColor,
    alignSelf: 'center',
    shadowColor: colors.primaryLightColor,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.58,
    shadowRadius: 2,
    elevation: 24,
  },
  buttonTitle: {
    fontSize: perfectSize(18),
    fontFamily: fonts.quicksandBold,
    color: colors.primaryTextColor,
  },
  bottomText: {
    textAlign: 'center',
    fontSize: perfectSize(14),
    color: colors.primaryLightColor,
    fontFamily: fonts.avenirLight,
    marginTop: '5%',
  },
});
